compressionLevel: mixed

enableGlobalCache: false

httpProxy: "${http_proxy:-}"

httpsProxy: "${http_proxy:-}"

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.com/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
