version: 2.1

orbs:
    node: circleci/node@4.1

jobs:
    build:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  name: Lerna Bootstrap
                  command: yarn lerna bootstrap

    test:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout

    publish:
        docker:
            - image: cimg/node:15.1
        steps:
            - run:
                  name: Lerna Publish
                  command: yarn lerna publish from-package
workflows:
    sample:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - publish:
                  requires:
                      - build
                      - test
                #   filters:
                    #   branches:
                    #       ignore: /.*/
                    #   tags:
                    #       only: /^\d+\.\d+\.\d+(-pre\.\d+)?$/
