version: 2.1

orbs:
    node: circleci/node@4.1

defaults: &defaults
    docker:
        - image: cimg/node:15.1
    working_directory: ~/repo

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  name: Lerna Bootstrap
                  command: yarn lerna bootstrap
            - persist_to_workspace:
                  root: ~/repo
                  paths: .
    test:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - checkout

    publish:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Lerna Publish
                  command: yarn lerna publish from-package --yes
                  
workflows:
    main:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - publish:
                  requires:
                      - test
                  filters:
                      branches:
                          only: /main/
                      tags:
                          only: /^\d+\.\d+\.\d+(-alpha\.\d+)?$/
