export enum ADD_RULE {
    TOP = "TOP",
    LEFT = "LEFT",
    BOTTOM = "BOTTOM",
    RIGHT = "RIGHT",
    TAB = "TAB",
}

export enum SLOT_EVENT {
    ADD_NODE = "ADD_NODE",
    ADD_PANEL = "ADD_PANEL",
    REMOVE_NODE = "REMOVE_NODE",
    REMOVE_PANEL = "REMOVE_PANEL",
    MOVE_SPLITTER = "MOVE_SPLITTER",
    SELECT_TAB = "SELECT_TAB",
    NODE_REMOVED = "NODE_REMOVED",
}
